#!/bin/bash

# load variables written in secret .config
source .config

# tunnel to remote and run shema.sql
export SSHPASS="$DB_PASSWORD"
sshpass -e ssh -L $DB_PORT:$DB_HOST:$DB_PORT $DB_USERNAME@dumbledore.encs.concordia.ca << ENDCOMMANDS
mysql -u$DB_USERNAME -p$DB_PASSWORD $DB_USERNAME << ENDSCHEMA
    $(cat "schema.sql")
ENDSCHEMA
sleep infinity
ENDCOMMANDS
